server:
  port: 8081
  
Spring:
  application:
    name: SWIGGY-APP

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
        default-zone: http://localhost:8761/
    