server:
  port: 8083

spring:
  application:
    name: RESTAURANT-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      default-zone: http://localhost:8761/
    